=== GUGANOG/ArmaIII-UVO/squad.dtd
<!ELEMENT squad (name, email, web?, picture?, title?, member+)>
<!ATTLIST squad nick CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT title (#PCDATA)>

<!ELEMENT member (name, email, icq?, msn?, remark?)>
<!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>

<!ELEMENT icq (#PCDATA)>
<!ELEMENT msn (#PCDATA)>
<!ELEMENT remark (#PCDATA)>

=== GUGANOG/ArmaIII-UVO/squad.xml
<?xml version="1.0"?>
<!DOCTYPE squad SYSTEM "squad.dtd">
<squad nick="AIMORÉ">
    <name>[Gpt de Emprego Imediato]</name>
    <email>-</email>
    <web>https://discord.gg/tRRaVdMhp3</web>
    <picture>Aimore.paa</picture>
    <title>- G P T  A I M O R É -</title>

    <member id="76561199850652965" nick="Dolph">
        <name>Gustavo</name>
        <email>-</email>
        <icq>DISCORD: dolph_68737</icq>
        <remark>Major</remark>
    </member>

    <member id="76561198112211475" nick="Poiva">
        <name>Jean</name>
        <email>-</email>
        <icq>DISCORD: </icq>
        <remark>Tenente</remark>
    </member>

    <member id="931939488" nick="Poiva">
        <name>Poiva</name>
        <email>-</email>
        <icq>DISCORD: </icq>
        <remark>Capitão</remark>
    </member>

    <member id="76561198300646636" nick="danni">
        <name>Danni</name>
        <email>-</email>
        <icq>DISCORD: - </icq>
        <remark>Tenente</remark>
    </member>

    <member id="76561199174539013" nick="kiosk">
        <name>Kiosk</name>
        <email>-</email>
        <icq>DISCORD: - </icq>
        <remark>Tenente</remark>
    </member>

    <member id="76561198873066923" nick="santo">
        <name>Santo</name>
        <email>-</email>
        <icq>DISCORD: - </icq>
        <remark>Tenente</remark>
    </member>

    <member id="76561198154336802" nick="Chronos">
        <name>Chronos</name>
        <email>-</email>
        <icq>DISCORD: - </icq>
        <remark>Tenente</remark>
    </member>
     
</squad>
